language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules

before_script:
  - npm run selenium-setup

script:
  - npm run build
  - npm run unit-tests
  - npm start &
  - npm run selenium-start &
  - npm run e2e-tests
  - pkill node
  
